### PR TITLE
Bugfix: disable transaction in dbxUpdate on demand

### PR DESCRIPTION
**Pull request by ghost**
if using a transaction block as described in the documentation for insert and delete, the update process breaks and has its own begin commit block. This is weird and should be fixed, I consider this a bug because of its unintended behavior.

Also, there is no documentation in your function description about the usage of the transactional block.

example:

```R
  dbWithTransaction(myConnection, {
    dbxUpdate(conn       = myConnection, 
              table      = "myTable", 
              records    = myTableDf, 
              where_cols = c("myId"))
    dbBreak()
  })
```

expected behavior: data is NOT updated, the statement has a rollback forced by `dbBreak()`

current behavior: data is updated, the rollback coming with `dbBreak()` comes too late

solutions:

* if you really need to encapsulate the updates in a transaction, make it optional (see pull request)
* if you don't need the transaction, just remove it

### CODE REVIEW

**Comment by ankane** [comment]
Hey @jottyfan, thanks for reporting and creating a PR. All database operations are intended to be atomic, which is why `dbxUpdate` starts a transaction. Ideally, the DBI object would expose the fact you're inside a transaction and it could disable / use savepoints instead. I may create a `dbxTransaction` method at some point to handle this automatically. In the meantime, I think the approach you've taken makes sense. A few suggestions:

1. Let's call the option `atomic`
2. Let's make the default `TRUE` for backwards compatibility
3. Instead of adding an additional option to `withTransaction`, I think it'd be good to create a new method like `maybeAtomic` which decides whether or not to call `withTransaction` or execute the code directly.

**Comment by ghost** [comment]
Hey @ankane , 

thanks for the quick response. I've updated my pull request the way you've suggested. Please let me know when a new release including this bugfix comes out.

Looking forward to have this extension available soon.

**Comment by ankane** [comment]
Awesome, thanks @jottyfan 👍

**Comment by ankane** [comment]
Hey @jottyfan, 0.2.6 has been released with this option, named `transaction` (thought it was more intuitive than `atomic` after thinking about it more). Thanks again for the PR!

**Comment by ghost** [comment]
> Hey @jottyfan, 0.2.6 has been released with this option, named `transaction` (thought it was more intuitive than `atomic` after thinking about it more). Thanks again for the PR!

That's great news, thank you very much!

**Pull request merged**
